name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Starting CI Process"


      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2'


      - name: run docker compose 
        run: docker compose up


      - uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: '30'


      - name: tests by using curl
        run: curl http://localhost:3000


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: upload image to ECR
        uses: appleboy/docker-ecr-action@master
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          repo: eitans/projects
          registry: ${{ secrets.AWS_REPOSITORY }}
